on: [push]

jobs:
  fib:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: fib
        uses: jkremser/fib-action@v1
        with:
          n: '42'
      - name: Get the output time
        run: echo "The result is ${{ steps.fib.outputs.result }}"
